apiVersion: v1
kind: Service
metadata:
  name: nginx-cluster-ip
spec:
  # type: ClusterIP   # default if no type is specified
  selector:
    project: expense  # labels same as of the target pod
    module: backend
    environment: dev
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port, can also use name if the container port has a name in the target pod definition