apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      # preferredDuringSchedulingIgnoredDuringExecution is a list of dictionaries
      # weight (1 to 100) is the priority assigned to the expression and the preference with least weight will have more priority
      # for example, the below expression will be preferred but if there is no node with this label the pod is still scheduled
      - weight: 1
        preference:
          matchExpressions:
          - key: another-node-label-key
            operator: In
            values:
            - another-node-label-value
  containers:
  # docker run -d --name nginx nginx
  - name: nginx
    image: nginx:stable-perl
  # nodeSelector:
  #   hardware: gpu
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"
    