kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  # here 'V' of place holder should be in upper case, whereas 'v' of values.yaml in lower case
  type: {{ .Values.service.type }}
  selector:
    tier: frontend
    app: nginx
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: {{ .Values.service.port }} # service port
    targetPort: 80 # container port